accounts/urls.py
from django.urls import path

from accounts.views import login_view, logout_view, profile_view, OrdersHistoryView

app_name = 'accounts'
urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('profile/', profile_view, name='profile'),
    path('orders-history/', OrdersHistoryView.as_view(), name='orders_history'),
]

order/urls.py
from django.urls import path
from order.views import (CreateOrder, AddOrderItem, order_result, )

app_name = 'order'
urlpatterns = [
    path('create-order/', CreateOrder.as_view(), name='create_order'),
    path('add-item/', AddOrderItem.as_view(), name='add_item'),
    path('order-result/', order_result, name='order_result'),
]

product/urls.py
from django.urls import path
from product.views import AllProductView, ProductDetailView, CategoryProductsListView

app_name = 'product'
urlpatterns = [
    path('', AllProductView.as_view(), name='all_products'),
    path('product/<int:pk>', ProductDetailView.as_view(), name='product_detail'),
    path('category/<int:pk>', CategoryProductsListView.as_view(), name='categories_products'),
]

shop/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    url(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    url(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    url(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    # setup URL for django flatpages
    path('pages/', include('django.contrib.flatpages.urls')),

    path('accounts/', include('accounts.urls')),
    path('', include('product.urls')),
    path('orders/', include('order.urls')),
    path('api/v1/', include('core.api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>کالاشاپ - {% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'base/base.css' %}">
    {% block style %}{% endblock %}

</head>
<body>
<nav class="navbar navbar-expand fixed-top">
    <div class="container flex-row-reverse">
        <a href="{% url 'product:all_products' %}" class="button-logo"><img
                src="{% static 'base/img/kalashop-logo.png' %}" alt="kalashop-logo"></a>
        <div class="navbar-collapse flex-column">
            <div class="navbar-nav ml-auto flex-row-reverse">
                <div class="input-group" style="width: 33.5rem">
                    <div class="input-group-prepend remove-btn">
                        <a href="#"><i class="fa fa-fw fa-close"></i></a>
                    </div>
                    <input class="input-search" type="text" placeholder="جستجو">
                    <div class="input-group-append search-btn">
                        <a href="#"><i class="fa fa-fw fa-search"></i></a>
                    </div>
                </div>
                {% if user.is_authenticated %}
                    <div style="width: 2rem;margin-right: 19rem;">
                        <div class="dropdown">
                            <a href="#"><i class="fa fa-fw fa-user" style="font-size:35px"></i></a>
                            <div class="dropdown-content card dropdown-user">
                                <div class="card-header">
                                    <h4>{{ user.first_name }} {{ user.last_name }}</h4>
                                </div>
                                <div class="card-body" style="text-align: right">
                                    <a href="{% url 'accounts:profile' %}">مشاهده حساب کاربری<i
                                            class="fa fa-fw fa-user-circle-o"></i></a><br>
                                    <a href="#">سفارش‌های من<i
                                            class="fa fa-fw fa-shopping-bag"></i></a><br>
                                    <a href="{% url 'accounts:logout' %}">خروج از حساب کاربری<i
                                            class="fa fa-fw fa-sign-out"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% else %}
                    <div style="width: 10rem;margin-right: 15rem">
                        <button class="auth-btn" data-toggle="modal"
                                data-target="#register-modal">ثبت‌نام
                        </button>
                        <button class="auth-btn"><a href="{% url 'accounts:login' %}">ورود<i class="fa fa-fw fa-user"
                                                                                             style="font-size:18px"></i></a>
                        </button>
                    </div>
                {% endif %}
                <div style="height: 1.5rem;border: 0.001mm ridge silver;margin-right: 10px;margin-top: 5px"></div>

                <p id="cart-quantity"></p>
                <div>

                    <button id="cart-btn" data-toggle="modal" data-target="#cart-modal"><i
                            class="fa fa-fw fa-shopping-cart"
                            style="font-size:35px;padding-left: 10px;cursor: pointer"></i></button>

                </div>

            </div>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#">تماس با کالاشاپ<i class="fa fa-fw fa-phone"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/about-us/">درباره کالاشاپ<i class="fa fa-fw fa-info-circle"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">تخفیف‌ها و پیشنهادها<i class="fa fa-fw fa-percent"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">سوپر مارکت<i class="fa fa-fw fa-shopping-basket"></i></a>
                </li>
                <li class="nav-item">
                    <div class="dropdown">
                        <a class="dropbtn nav-link" href="#">دسته‌بندی کالاها<i class="fa fa-fw fa-bars"></i></a>
                        <div class="dropdown-content dropdown-cat">
                            <a href="#">کالای دیجیتال<i class="fa fa-fw fa-laptop"></i></a>
                            <a href="#">کالاهای سوپرمارکتی<i class="fa fa-fw fa-shopping-basket"></i></a>
                            <a href="#">لوازم جانبی<i class="fa fa-fw fa-headphones"></i></a>
                            <a href="#">اسباب‌‌ بازی، کودک و نوزاد<i class="fa fa-fw fa-child"></i></a>
                            <a href="#">زیبایی و سلامت<i class="fa fa-fw fa-heart"></i></a>
                            <a href="#">خانه و آشپزخانه<i class="fa fa-fw fa-table"></i></a>
                            <a href="#">کتاب، لوازم‌التحریر و هنر<i class="fa fa-fw fa-pencil"></i></a>
                            <a href="#">ورزش و سفر<i class="fa fa-fw fa-soccer-ball-o"></i></a>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container-fluid">
    {% block modal %}{% endblock %}
    <div class="modal fade" id="register-modal">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-body">
                    <form method="POST" action="{% url 'send_info' %}" id="register-form" enctype="multipart/form-data">

                        <div class="form-group" id="reg-mobile-group">
                            <label for="reg-mobile">:شماره موبایل</label>
                            <input type="text" class="form-control" name="reg-mobile" id="reg-mobile">
                        </div>
                        <div class="form-group" id="first_name-group">
                            <label for="reg-first_name">:نام</label>
                            <input type="text" class="form-control" name="reg-first_name" id="reg-first_name">
                        </div>
                        <div class="form-group" id="last_name-group">
                            <label for="reg-last_name">:نام‌خانوادگی</label>
                            <input type="text" class="form-control" name="reg-last_name" id="reg-last_name">
                        </div>
                        <div class="form-group" id="email-group">
                            <label for="reg-email">:ایمیل</label>
                            <input type="text" class="form-control" name="reg-email" id="reg-email">
                        </div>
                        <div class="form-group" id="reg-password-group">
                            <label for="reg-password">:رمز عبور</label>
                            <input type="password" class="form-control" name="reg-password" id="reg-password">
                        </div>
                        <div class="form-group" id="reg-password2-group">
                            <label for="reg-password2">:تکرار رمز عبور</label>
                            <input type="password" class="form-control" name="reg-password2" id="reg-password2">
                        </div>

                        <button type="button" class="btn btn-danger mr-3" data-dismiss="modal">انصراف</button>
                        <button type="submit" class="btn btn-submit mr-0" style="width: 8rem" id="send-info-btn">
                            دریافت کد تأیید
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="otp-modal">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-body">
                    <form method="POST" action="{% url 'verify_otp' %}" id="otp-form" enctype="multipart/form-data">

                        <div class="form-group" id="otp-group">
                            <label for="otp">:لطفاً کد تأیید ۶رقمی ارسال شده به گوشی خود را وارد کنید</label>
                            <input type="number" class="form-control" name="otp" id="otp" maxlength="6" minlength="6">
                        </div>
                        <div id="otp-btn-group">
                            <button type="button" class="btn btn-danger mr-3" data-dismiss="modal">انصراف</button>
                            <button type="submit" class="btn btn-submit mr-0" id="verify-otp-btn">
                                ارسال
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="cart-modal">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-body">
                    <div class="mb-4">
                        <h4 id="cart-total-price" class="text-dark"></h4>
                    </div>
                    <div id="cart-btn-group">
                        <button class="btn btn-danger mr-3 mb-2" data-dismiss="modal">بستن</button>

                        <button class="btn btn-submit mr-1 mb-2"><a class="text-white"
                                                                    href="{% url 'order:create_order' %}">ثبت
                            سفارش</a></button>


                    </div>
                </div>
            </div>
        </div>
    </div>
    {% block content %}{% endblock %}
</div>
<script src="{% static 'base/base.js' %}"></script>
<script src="{% static 'accounts/js/register.js' %}"></script>
{% block script %}
{% endblock %}
</body>
</html>