product/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from product.api.views import ProductListView, CategoryListView, ProductListByCategory

urlpatterns = [
    path('products/', ProductListView.as_view(), name='all_products'),
    path('categories/', CategoryListView.as_view(), name='all_categories'),
    path('category/<int:category_id>', ProductListByCategory.as_view(), name='category_products'),
]

product/urls.py
from django.urls import path
from product.views import AllProductView, ProductDetailView, CategoryProductsListView

app_name = 'product'
urlpatterns = [
    path('', AllProductView.as_view(), name='all_products'),
    path('product/<int:pk>', ProductDetailView.as_view(), name='product_detail'),
    path('category/<int:pk>', CategoryProductsListView.as_view(), name='categories_products'),
]

shop/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    url(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    url(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    url(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    # setup URL for django flatpages
    path('pages/', include('django.contrib.flatpages.urls')),

    path('accounts/', include('accounts.urls')),
    path('', include('product.urls')),
    path('orders/', include('order.urls')),
    path('api/v1/', include('core.api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

product/models.py
from datetime import datetime

from django.conf import settings
from django.core.validators import MaxValueValidator
from django.db import models
from django.db.models import Avg, Count
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext as _
from shop.utils import product_image_path


# Create your models here.
class Category(models.Model):
    name = models.CharField(_('عنوان'), max_length=30, unique=True)
    parent_category = models.ForeignKey('self', blank=True, null=True, on_delete=models.CASCADE,
                                        related_name='children', verbose_name=_('دسته بندی پدر'))
    icon = models.CharField(_('آیکون فونت'), max_length=30)

    class Meta:
        verbose_name_plural = 'دسته‌بندی‌ها'
        verbose_name = 'دسته‌بندی'

    def __str__(self):
        return self.name


class Color(models.Model):
    name = models.CharField(_('نام رنگ'), max_length=200, unique=True)

    class Meta:
        verbose_name_plural = 'رنگ‌ها'
        verbose_name = 'رنگ'

    def __str__(self):
        return self.name


# product additional media: video or additional images
class ProductMedia(models.Model):
    name = models.CharField(_('نام محصول موردنظر'), max_length=150)
    image = models.ImageField(_('بارگزاری تصویر محصول'), upload_to=product_image_path)
    date_created = models.DateTimeField(_('تاریخ بارگزاری تصویر'), auto_now_add=True)

    class Meta:
        ordering = ['date_created']
        verbose_name_plural = 'عکس‌های محصولات'
        verbose_name = 'عکس محصول'

    def __str__(self):
        return self.name

    def image_tag(self):
        return mark_safe('<img src="/media/%s" width="50" height="50" />' % (self.image))

    image_tag.short_description = 'Image'


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products',
                                 verbose_name=_('دسته بندی'))
    name_fa = models.CharField(_('نام فارسی'), max_length=200, unique=True)
    name_en = models.CharField(_('نام انگلیسی'), max_length=200, unique=True)
    images = models.ManyToManyField(ProductMedia, blank=True, related_name='products', verbose_name=_('تصاویر'))
    description = models.TextField(_('توضیحات محصول'), )
    colors = models.ManyToManyField(Color, blank=True, related_name='products', verbose_name=_('رنگ‌ها'))
    inventory = models.IntegerField(_('موجودی'), default=0)
    price = models.IntegerField(_('قیمت (به تومان)'), )
    date_created = models.DateTimeField(_('تاریخ ایجاد محصول'), auto_now_add=True)

    class Meta:
        ordering = ['date_created']
        verbose_name_plural = 'محصولات'
        verbose_name = 'محصول'

    def __str__(self):
        return self.name_fa

    @property
    def final_price(self):
        discounts = ProductDiscount.objects.all()
        for discount in discounts:
            if self in discount.products.all():
                return int(self.price - (self.price * discount.amount / 100))
        return self.price

    @property
    def voters_number(self):
        product = Product.objects.filter(id=self.id).annotate(voters_num=Count('rates'))
        return product[0].voters_num

    @property
    def rate_average(self):
        product = Product.objects.filter(id=self.id).annotate(rates_avg=Avg('rates'))
        if not product[0].rates_avg:
            return 0
        return product[0].rates_avg


# Each product has its especial guarantees.
class Guarantee(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='guarantees',
                                verbose_name=_('محصول موردنظر'))
    name = models.CharField(_('عنوان گارانتی'), max_length=200)
    amount = models.IntegerField(_('قیمت (به تومان)'), )

    class Meta:
        verbose_name_plural = 'گارانتی مجصولات'
        verbose_name = 'گارانتی'

    def __str__(self):
        return self.name


class ProductDiscount(models.Model):
    products = models.ManyToManyField(Product, related_name='discounts', verbose_name=_('محصولات موردنظر'))
    amount = models.PositiveSmallIntegerField(_('درصد تخفیف'), validators=[MaxValueValidator(100)])

    class Meta:
        verbose_name_plural = 'تخفیفات کلی محصولات'
        verbose_name = 'تخفیف'

    def __str__(self):
        return f'{self.amount}%'


class ProductRate(models.Model):
    # rate levels:
    one = 1
    two = 2
    three = 3
    four = 4
    five = 5
    rate_levels = (
        (one, 1),
        (two, 2),
        (three, 3),
        (four, 4),
        (five, 5),
    )
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='rates',
                                verbose_name=_('محصول موردنظر'))
    customer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.RESTRICT, related_name='rates',
                                 verbose_name=_('امتیاز دهنده'))
    rate_level = models.IntegerField(_('امتیاز'), choices=rate_levels)

    class Meta:
        verbose_name_plural = 'امتیازات محصولات'
        verbose_name = 'امتیاز محصول'

    def __str__(self):
        return f'{self.product}, {self.customer}, {self.rate_level}'


class ProductComment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='comments',
                                verbose_name=_('محصول موردنظر'))
    customer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.RESTRICT, related_name='comments',
                                 verbose_name=_('نظر دهنده'))
    text = models.TextField(_('متن نظر (یا دیدگاه)'), )

    class Meta:
        verbose_name_plural = 'نظرات محصولات'
        verbose_name = 'نظر درباره محصول'

    def __str__(self):
        return f'{self.product}, {self.customer}'

product/forms.py
from django import forms

product/api/views.py
from rest_framework import generics, viewsets
from rest_framework.pagination import PageNumberPagination
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from product.api.serializer import ProductSerializer, CategorySerializer
from product.models import Product, Category


class ProductResultsPagination(PageNumberPagination):
    page_size = 2
    page_size_query_param = 'page_size'
    max_page_size = 3

    def get_paginated_response(self, data):
        return Response({
            'next': self.get_next_link(),
            'previous': self.get_previous_link(),
            'count': self.page.paginator.count,
            'results': data,
            'num_pages': self.page.paginator.num_pages,
        })


# a view show list of all the products for homepage of the project.
class ProductListView(generics.ListAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    pagination_class = ProductResultsPagination


# a view show list of all categories.
class CategoryListView(generics.ListAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer


# a view show list of all the products for determined by the category.
class ProductListByCategory(generics.ListAPIView):
    serializer_class = ProductSerializer
    pagination_class = ProductResultsPagination

    def get_queryset(self):
        category = self.kwargs['category_id']
        return Product.objects.filter(category__id=category)

product/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic import TemplateView, DetailView

from product.models import Product, Category


# Create your views here.

class AllProductView(TemplateView):
    template_name = 'product/all-products.html'


class ProductDetailView(DetailView):
    model = Product
    template_name = 'product/product-detail.html'


class CategoryProductsListView(DetailView):
    model = Category
    template_name = 'product/category-products.html'

templates/product/all-products.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}همه محصولات{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-12 col-md-9">
            <div class="row ord-row">
                <div class="col-12">
                    <p style="padding-right: 2px">فروشگاه اینترنتی کالاشاپ / <a class="text-primary"
                                                                                href="{% url 'product:all_products' %}">همه
                        محصولات</a></p>
                    <div class="card ord-card">
                        <div class="card-body row flex-row-reverse">
                            <p class="card-text">:مرتب سازی براساس&nbsp<i class="fa fa-fw fa-list-ol"></i></p>
                            <div class="ord-links">
                                <button href="#">ارزان‌ترین</button>
                                <button href="#">گران‌ترین</button>
                                <button href="#">پرفروش‌ترین</button>
                                <button href="#" class="bg-primary text-light">جدید‌ترین</button>
                                <button href="#">پربازدید‌ترین</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row products-row">
            </div>
            <div class="pagination">
            </div>
        </div>
        <div class="d-none d-md-block col-md-3">
            <div class="card side p-2 mt-3"
                 style="background-image: url({% static 'base/img/free-ship.png' %});background-repeat: no-repeat">
                <h6>ارسال رایگان سفارش</h6>
                <p style="font-size: 15px;color:darkgrey">سفارش های بالای ۳۰۰هزار تومان</p>
            </div>
            <div class="card side mt-3">
                <div class="card-header">
                    <p class="card-text row flex-row-reverse" style="font-size: 18px; margin-right: 2px">جستجو در
                        نتایج</p>
                </div>
                <div class="card-body">
                    <div class="input-group">
                        <input class="search-res" type="text" placeholder="جستجو">
                        <div class="input-group-append search-btn">
                            <a href="#"><i class="fa fa-fw fa-search"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script src="{% static 'product/js/all-products.js' %}"></script>
{% endblock %}

templates/product/category-products.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}دسته بندی {{ category.name }}{% endblock %}

{% block content %}
    <p class="d-none" id="category-id">{{ category.id }}</p>
    <div class="row">
        <div class="col-12 col-md-9">
            <div class="row ord-row">
                <div class="col-12">
                    <p style="padding-right: 2px">فروشگاه اینترنتی کالاشاپ / <a class="text-primary"
                                                                                href="{% url 'product:categories_products' category.id %}">{{ category.name }}</a>
                    </p>
                    <div class="card ord-card">
                        <div class="card-body row flex-row-reverse">
                            <p class="card-text">:مرتب سازی براساس&nbsp<i class="fa fa-fw fa-list-ol"></i></p>
                            <div class="ord-links">
                                <button href="#">ارزان‌ترین</button>
                                <button href="#">گران‌ترین</button>
                                <button href="#">پرفروش‌ترین</button>
                                <button href="#" class="bg-primary text-light">جدید‌ترین</button>
                                <button href="#">پربازدید‌ترین</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row products-row">
            </div>
            <div class="pagination">
            </div>
        </div>
        <div class="d-none d-md-block col-md-3">
            <div class="card side p-2 mt-3"
                 style="background-image: url({% static 'base/img/free-ship.png' %});background-repeat: no-repeat">
                <h6>ارسال رایگان سفارش</h6>
                <p style="font-size: 15px;color:darkgrey">سفارش های بالای ۳۰۰هزار تومان</p>
            </div>
            <div class="card side mt-3">
                <div class="card-header">
                    <p class="card-text row flex-row-reverse" style="font-size: 18px; margin-right: 2px">جستجو در
                        نتایج</p>
                </div>
                <div class="card-body">
                    <div class="input-group">
                        <input class="search-res" type="text" placeholder="جستجو">
                        <div class="input-group-append search-btn">
                            <a href="#"><i class="fa fa-fw fa-search"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script src="{% static 'product/js/category-products.js' %}"></script>
{% endblock %}

templates/product/product-detail.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}{{ product.name_fa }}{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'product/css/product.css' %}">
{% endblock %}

{% block content %}
    <div class="row card-group" id="product-info">
        <div class="col-7" id="product-details">
            <div class="card">
                <div class="card-body">
                    <h4 id="name-fa">{{ product.name_fa }}</h4>
                    <p>{{ product.name_en }}</p>
                    <p>____________________________________________________________________________</p>
                    <div class="row" style="direction: rtl;margin-right: 0">
                        <i class="fa fa-fw fa-star" style="color: yellow;font-size: 15px;margin-top: 3px"></i>
                        <p>{{ product.rate_average }}</p>
                        <div style="height: 1.2rem;border: 0.001mm ridge grey;margin-right: 2rem;margin-left: 2rem;"></div>
                        <p><a class="text-primary" href="#comments">{{ product.voters_number }}</a> دیدگاه کاربران</p>
                        <div style="height: 1.2rem;border: 0.001mm ridge grey;margin-right: 2rem;margin-left: 2rem;"></div>
                        <p>دسته‌بندی: <a class="text-primary" href="#">{{ product.category }}</a></p>
                    </div>
                    <div class="list-group">
                        <form id="product-form">
                            <div class="form-group d-none" id="product-id-group">
                                <label for="product-id"></label>
                                <input type="number" id="product-id" value="{{ product.id }}">
                            </div>
                            <div class="form-group d-none" id="image-group">
                                <label for="image"></label>
                                <input type="text" id="image" value="{{ product.images.all.0.image.url }}">
                            </div>
                            <div class="form-group d-none" id="price-group">
                                <label for="price"></label>
                                <input type="number" id="price" value="{{ product.final_price }}">
                            </div>
                            <div class="form-group d-none" id="inventory-group">
                                <label for="inventory"></label>
                                <input type="number" id="inventory" value="{{ product.inventory }}">
                            </div>
                            <div class="form-group row" id="color-group">
                                <label class="col-0" for="color">رنگ:&nbsp;</label>
                                <select class="form-control col-4" id="color">
                                    {% for color in product.colors.all %}
                                        <option>{{ color.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group row" id="guarantee-group">
                                <label class="col-0" for="guarantee">گارانتی:&nbsp;</label>
                                <select class="form-control col-4" id="guarantee">
                                    {% for guarantee in product.guarantees.all %}
                                        <option>{{ guarantee.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group row" id="quantity-group">
                                <label class="col-0" for="quantity">تعداد:&nbsp;</label>
                                <div class="btn btn-info" id="decrease" onclick="decreaseValue()">-
                                </div>
                                <input type="number" class="col-0 form-control" id="quantity" value="1" min="1"
                                       max="{{ product.inventory }}">
                                <div class="btn btn-info" id="increase" onclick="increaseValue()">+
                                </div>
                            </div>
                            <p style="font-size: large;color: rgba(0,0,0,0.76)">موجودی کالا: {{ product.inventory }}
                                عدد</p>
                            {% if product.price == product.final_price %}
                                <h4>{{ product.final_price }} تومان</h4>
                            {% else %}
                                <h5><del>{{ product.price }} تومان</del></h5>
                                <h4>{{ product.final_price }} تومان</h4>
                            {% endif %}
                            <button class="btn btn-submit" id="add-product{{ product.id }}">افزودن به سبد
                                خرید
                            </button>
                        </form>

                    </div>
                </div>

            </div>
        </div>
        <div class="col-5" id="product-images">
            <div class="card pb-2">
                <div class="w3-content" style="max-width:1200px">
                    {% for image in product.images.all %}
                        <img alt="{{ image.name }}" class="mySlides" id="img-{{ forloop.counter }}"
                             src="{{ image.image.url }}"
                             style="display:none">
                    {% endfor %}
                    <div class="w3-row-padding w3-section" style="margin-top: 1rem">
                        {% for image in product.images.all %}
                            <div class="w3-col s3 ml-1">
                                <img alt="{{ image.name }}" class="demo w3-opacity w3-hover-opacity-off"
                                     src="{{ image.image.url }}"
                                     style="width:100%;cursor:pointer" onclick="currentDiv({{ forloop.counter }})">
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script src="{% static 'product/js/product.js' %}"></script>
{% endblock %}