accounts/api/urls.py
from django.urls import path, include

from accounts.api.views import (GetRegistrationInfoView, VerifyRegistrationOTPView, ChangePasswordView,
                                VerifyOTPResetPassword, RequestResetPasswordEmail, RequestResetPasswordMobile,
                                ConfirmResetPassword, AddAddressView, EditRemoveAddressView, ChangeMobileView,
                                VerifyOTPChangeMobile)

urlpatterns = [
    path('register/', GetRegistrationInfoView.as_view(), name='send_info'),
    path('verify-otp/', VerifyRegistrationOTPView.as_view(), name='verify_otp'),
    path('change-mobile/', ChangeMobileView.as_view(), name='change_mobile'),
    path('change-mobile/verify-otp/', VerifyOTPChangeMobile.as_view(), name='verify_otp_change_mobile'),
    path('change-password/<int:pk>', ChangePasswordView.as_view(), name='change_password'),
    path('add-address/', AddAddressView.as_view(), name='add_address'),
    path('edit-address/<int:pk>', EditRemoveAddressView.as_view(), name='edit_remove_address'),
    path('password-reset/by-email/', RequestResetPasswordEmail.as_view(), name='reset_password_email'),
    path('password-reset/by-mobile/', RequestResetPasswordMobile.as_view(), name='reset_password_mobile'),
    path('password-reset/verify-otp/', VerifyOTPResetPassword.as_view(), name='verify_otp_reset_password'),
    path('password-reset/confirm/', ConfirmResetPassword.as_view(), name='confirm_reset_password'),
]

order/api/urls.py
from django.urls import path, include

from order.api.views import AddOrderItemsView, CheckCouponView

urlpatterns = [
    path('add-items/', AddOrderItemsView.as_view(), name='add_items'),
    path('check-coupon/', CheckCouponView.as_view(), name='check_coupon'),
]

order/urls.py
from django.urls import path
from order.views import (CreateOrder, AddOrderItem, order_result, )

app_name = 'order'
urlpatterns = [
    path('create-order/', CreateOrder.as_view(), name='create_order'),
    path('add-item/', AddOrderItem.as_view(), name='add_item'),
    path('order-result/', order_result, name='order_result'),
]

product/urls.py
from django.urls import path
from product.views import AllProductView, ProductDetailView, CategoryProductsListView

app_name = 'product'
urlpatterns = [
    path('', AllProductView.as_view(), name='all_products'),
    path('product/<int:pk>', ProductDetailView.as_view(), name='product_detail'),
    path('category/<int:pk>', CategoryProductsListView.as_view(), name='categories_products'),
]

shop/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    url(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    url(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    url(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    # setup URL for django flatpages
    path('pages/', include('django.contrib.flatpages.urls')),

    path('accounts/', include('accounts.urls')),
    path('', include('product.urls')),
    path('orders/', include('order.urls')),
    path('api/v1/', include('core.api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

order/models.py
from django.conf import settings
from django.db import models
from django.core.validators import MaxValueValidator

from accounts.models import Address
from product.models import Product
from django.utils.translation import ugettext as _


# Create your models here.
class Order(models.Model):
    # shipping types
    pishtaz = 'پیشتاز'
    sefareshi = 'سفارشی'
    shipping_types = ((pishtaz, 'پیشتاز'), (sefareshi, 'سفارشی'))

    # order status
    cancel = 'انصراف'
    active = 'فعال'
    bargiri = 'بارگیری'
    delivery = 'پیک'
    sent = 'تحویل'
    order_status = (
        (cancel, 'انصراف'),
        (active, 'فعال'),
        (bargiri, 'پرداخت موفق و درحال بارگیری از انبار'),
        (delivery, 'درحال ارسال توسط پیک'),
        (sent, 'تحویل سفارش به مشتری'),
    )
    customer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.RESTRICT, related_name='orders',
                                 verbose_name=_('کاربر'))
    datetime = models.DateTimeField(_('تاریخ '), auto_now_add=True)
    shipping = models.CharField(_('نوع پست'), choices=shipping_types, max_length=20, default=sefareshi)
    status = models.CharField(_('وضعیت'), choices=order_status, max_length=20, default=bargiri)
    address = models.ForeignKey(Address, on_delete=models.RESTRICT, related_name='orders', verbose_name=_('آدرس'))

    class Meta:
        verbose_name_plural = 'سفارش‌ها'
        verbose_name = 'سفارش'

    def __str__(self):
        return self.id


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items', verbose_name=_('سفارش'))
    product = models.ForeignKey(Product, on_delete=models.RESTRICT, verbose_name=_('محصول'))
    quantity = models.PositiveIntegerField(_('تعداد'), )

    class Meta:
        verbose_name_plural = 'آیتم‌های سفارش'
        verbose_name = 'آیتم سفارش'

    def __str__(self):
        return f'{self.product} - {self.quantity}'

    @property
    def total_item_price(self):
        return self.quantity * self.product.final_price


class Coupon(models.Model):
    customers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='coupons',
                                       verbose_name=_('کاربران موردنظر'))
    code = models.CharField(_('کد تخفیف'), max_length=15)
    amount = models.PositiveSmallIntegerField(_('درصد تخفیف'), validators=[MaxValueValidator(100)])
    expire_date = models.DateField(_('تاریخ انقضاء'), blank=True, null=True)

    class Meta:
        verbose_name_plural = 'کدهای تخفیف'
        verbose_name = 'کد تخفیف'

    def __str__(self):
        return f'{self.code} - {self.amount}%'

order/forms.py
from django import forms
from order.models import Order, OrderItem


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['shipping', 'address', ]
        widgets = {
            'shipping': forms.Select(attrs={'class': 'form-control col-5'}),
        }
        error_messages = {
            'address': {'required': '.آدرس انتخاب نشده'}
        }


class OrderItemForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        fields = '__all__'

order/api/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView

from order.api.serializer import OrderItemSerializer
from order.models import OrderItem, Coupon


class AddOrderItemsView(APIView):

    def get(self, request):
        customers = OrderItem.objects.all()
        serializer = OrderItemSerializer(customers, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)

    def post(self, request):
        print('*' * 100)
        print(request.data)
        serializer = OrderItemSerializer(data=request.data, many=True)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class CheckCouponView(APIView):

    def post(self, request):
        coupon = Coupon.objects.get(code=request.data['coupon'], customers=request.user)
        if coupon:
            return Response({'amount': coupon.amount, 'code': coupon.code}, status=status.HTTP_200_OK)
        return Response({'code': ['کد واردشده معتبر نیست.']}, status=status.HTTP_406_NOT_ACCEPTABLE)

order/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.generic import CreateView

from order.forms import OrderForm, OrderItemForm
from order.models import Order, OrderItem, Coupon


# Create your views here.

class CreateOrder(LoginRequiredMixin, CreateView):
    model = Order
    form_class = OrderForm
    template_name = 'order/create-order.html'
    success_url = '/orders/add-item/'

    def form_valid(self, form):
        form.instance.customer = self.request.user
        super().form_valid(form)
        return render(self.request, 'order/add-item.html', context={'order_id': self.object.id})


class AddOrderItem(LoginRequiredMixin, CreateView):
    model = OrderItem
    form_class = OrderItemForm
    template_name = 'order/add-item.html'
    success_url = '/orders/add-item/'


def order_result(request):
    if request.method == 'POST':
        try:
            user_coupon = Coupon.objects.get(code=request.POST['del-coupon'])
            user_coupon.customers.remove(request.user)
            user_coupon.save()
            return render(request, 'order/order-result.html')
        except (KeyError, Coupon.DoesNotExist):
            return render(request, 'order/order-result.html')
    return render(request, 'order/order-result.html')

order/templates/order/add-item.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}ثبت سفارش{% endblock %}


{% block content %}
    <p id="order-id">{{ order_id }}</p>
    <form method="POST" action="{% url 'order:add_item' %}" class="d-none" id="add-item-form">
        {% csrf_token %}
        <div class="form-group" id="product-group">
            <label for="{{ form.product.id_for_label }}"></label>
            <input type="text" class="form-control" name="product" id="product">
        </div>
        <div class="form-group" id="order-group">
            <label for="{{ form.order.id_for_label }}"></label>
            <input type="text" class="form-control" name="order" id="order">
        </div>
        <div class="form-group" id="quantity-group">
            <label for="{{ form.quantity.id_for_label }}"></label>
            <input type="text" class="form-control" name="quantity" id="quantity">
        </div>
        <button type="submit">sub</button>
    </form>
{% endblock %}

{% block script %}
    <script src="{% static 'order/js/add-item.js' %}"></script>
{% endblock %}

order/templates/order/create-order.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}ثبت سفارش{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'order/css/create-order.css' %}">
{% endblock %}

{% block content %}
    <div class="row create-order-row">
        <div class="card col-7">
            <form id="create-order-form"></form>
            <table id="items-table" class="table table-striped" style="direction: rtl">
                <thead>
                <tr>
                    <th scope="col">تصویر</th>
                    <th scope="col">نام</th>
                    <th scope="col">قیمت واحد</th>
                    <th scope="col">تعداد</th>
                    <th scope="col">قیمت نهایی</th>
                    <th scope="col">حذف</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td id="item-image"><img style="width: 5rem" src=""></td>
                    <td id="item-name"></td>
                    <td id="item-price"></td>
                    <td id="item-count"></td>
                    <td id="item-final_price"></td>
                    <td class="item-delete"><i style="font-size: x-large" class="fa fa-fw fa-trash"></i>
                    </td>
                </tr>
                </tbody>
            </table>
            <div class="row">
                <div class="col-2">
                    <button class="btn btn-secondary" id="add-address-btn"><a class="text-white" href="{% url 'order:add_address' %}">واردکردن آدرس جدید</a></button>
                </div>
                <div class="col-10">
                    <form method="POST" id="create-order-form">
                        {% csrf_token %}
                        {% for error in form.non_field_errors %}
                            <p class="text-danger">{{ error }}*</p>
                        {% endfor %}
                        {% for error in form.items.errors %}
                            <p class="text-danger">{{ error }}*</p>
                        {% endfor %}
                        {% for error in form.shipping.errors %}
                            <p class="text-danger">{{ error }}*</p>
                        {% endfor %}
                        {% for error in form.address.errors %}
                            <p class="text-danger">{{ error }}*</p>
                        {% endfor %}
                        <div class="form-group row d-none" id="items-group">
                            <label class="col-0" for="{{ form.items.id_for_label }}">پست:&nbsp;</label>
                            {{ form.items }}
                        </div>
                        <div class="form-group row" id="shipping-group">
                            <label class="col-0" for="{{ form.shipping.id_for_label }}">پست:&nbsp;</label>
                            {{ form.shipping }}
                        </div>
                        <div class="form-group row" id="address-group">
                            <label class="col-0" for="{{ form.address.id_for_label }}">آدرس:&nbsp;</label>
                            <select type="text" class="form-control col-10" name="address" id="id_address">
                                {% for address in user.addresses.all %}
                                    <option value="{{ address.id }}">{{ address }}</option>
                                {% endfor %}
                            </select>
                        </div>

                        <button type="submit" class="btn btn-submit" id="payment-btn">پرداخت
                            و ثبت نهایی سفارش
                        </button>
                        <button type="button" class="btn btn-danger mr-3"><a class="text-white"
                                                                             href="{% url 'product:all_products' %}">انصراف</a>
                        </button>

                    </form>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

{% block script %}
    <script src="{% static 'order/js/create-order.js' %}"></script>
{% endblock %}