order/api/urls.py
from django.urls import path, include

from order.api.views import AddOrderItemsView, CheckCouponView

urlpatterns = [
    path('add-items/', AddOrderItemsView.as_view(), name='add_items'),
    path('check-coupon/', CheckCouponView.as_view(), name='check_coupon'),
]

order/urls.py
from django.urls import path
from order.views import (CreateOrder, AddOrderItem, order_result, )

app_name = 'order'
urlpatterns = [
    path('create-order/', CreateOrder.as_view(), name='create_order'),
    path('add-item/', AddOrderItem.as_view(), name='add_item'),
    path('order-result/', order_result, name='order_result'),
]

product/urls.py
from django.urls import path
from product.views import AllProductView, ProductDetailView, CategoryProductsListView

app_name = 'product'
urlpatterns = [
    path('', AllProductView.as_view(), name='all_products'),
    path('product/<int:pk>', ProductDetailView.as_view(), name='product_detail'),
    path('category/<int:pk>', CategoryProductsListView.as_view(), name='categories_products'),
]

shop/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    url(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    url(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    url(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    # setup URL for django flatpages
    path('pages/', include('django.contrib.flatpages.urls')),

    path('accounts/', include('accounts.urls')),
    path('', include('product.urls')),
    path('orders/', include('order.urls')),
    path('api/v1/', include('core.api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

order/models.py
from django.conf import settings
from django.db import models
from django.core.validators import MaxValueValidator

from accounts.models import Address
from product.models import Product
from django.utils.translation import ugettext as _


# Create your models here.
class Order(models.Model):
    # shipping types
    pishtaz = 'پیشتاز'
    sefareshi = 'سفارشی'
    shipping_types = ((pishtaz, 'پیشتاز'), (sefareshi, 'سفارشی'))

    # order status
    cancel = 'انصراف'
    active = 'فعال'
    bargiri = 'بارگیری'
    delivery = 'پیک'
    sent = 'تحویل'
    order_status = (
        (cancel, 'انصراف'),
        (active, 'فعال'),
        (bargiri, 'پرداخت موفق و درحال بارگیری از انبار'),
        (delivery, 'درحال ارسال توسط پیک'),
        (sent, 'تحویل سفارش به مشتری'),
    )
    customer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.RESTRICT, related_name='orders',
                                 verbose_name=_('کاربر'))
    datetime = models.DateTimeField(_('تاریخ '), auto_now_add=True)
    shipping = models.CharField(_('نوع پست'), choices=shipping_types, max_length=20, default=sefareshi)
    status = models.CharField(_('وضعیت'), choices=order_status, max_length=20, default=bargiri)
    address = models.ForeignKey(Address, on_delete=models.RESTRICT, related_name='orders', verbose_name=_('آدرس'))

    class Meta:
        verbose_name_plural = 'سفارش‌ها'
        verbose_name = 'سفارش'

    def __str__(self):
        return self.id


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items', verbose_name=_('سفارش'))
    product = models.ForeignKey(Product, on_delete=models.RESTRICT, verbose_name=_('محصول'))
    quantity = models.PositiveIntegerField(_('تعداد'), )

    class Meta:
        verbose_name_plural = 'آیتم‌های سفارش'
        verbose_name = 'آیتم سفارش'

    def __str__(self):
        return f'{self.product} - {self.quantity}'

    @property
    def total_item_price(self):
        return self.quantity * self.product.final_price


class Coupon(models.Model):
    customers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='coupons',
                                       verbose_name=_('کاربران موردنظر'))
    code = models.CharField(_('کد تخفیف'), max_length=15)
    amount = models.PositiveSmallIntegerField(_('درصد تخفیف'), validators=[MaxValueValidator(100)])
    expire_date = models.DateField(_('تاریخ انقضاء'), blank=True, null=True)

    class Meta:
        verbose_name_plural = 'کدهای تخفیف'
        verbose_name = 'کد تخفیف'

    def __str__(self):
        return f'{self.code} - {self.amount}%'

order/forms.py
from django import forms
from order.models import Order, OrderItem


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['shipping', 'address', ]
        widgets = {
            'shipping': forms.Select(attrs={'class': 'form-control col-5'}),
        }
        error_messages = {
            'address': {'required': '.آدرس انتخاب نشده'}
        }


class OrderItemForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        fields = '__all__'

order/api/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView

from order.api.serializer import OrderItemSerializer
from order.models import OrderItem, Coupon


class AddOrderItemsView(APIView):

    def get(self, request):
        customers = OrderItem.objects.all()
        serializer = OrderItemSerializer(customers, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)

    def post(self, request):
        print('*' * 100)
        print(request.data)
        serializer = OrderItemSerializer(data=request.data, many=True)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class CheckCouponView(APIView):

    def post(self, request):
        coupon = Coupon.objects.get(code=request.data['coupon'], customers=request.user)
        if coupon:
            return Response({'amount': coupon.amount, 'code': coupon.code}, status=status.HTTP_200_OK)
        return Response({'code': ['کد واردشده معتبر نیست.']}, status=status.HTTP_406_NOT_ACCEPTABLE)

order/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.generic import CreateView

from order.forms import OrderForm, OrderItemForm
from order.models import Order, OrderItem, Coupon


# Create your views here.

class CreateOrder(LoginRequiredMixin, CreateView):
    model = Order
    form_class = OrderForm
    template_name = 'order/create-order.html'
    success_url = '/orders/add-item/'

    def form_valid(self, form):
        form.instance.customer = self.request.user
        super().form_valid(form)
        return render(self.request, 'order/add-item.html', context={'order_id': self.object.id})


class AddOrderItem(LoginRequiredMixin, CreateView):
    model = OrderItem
    form_class = OrderItemForm
    template_name = 'order/add-item.html'
    success_url = '/orders/add-item/'


def order_result(request):
    if request.method == 'POST':
        try:
            user_coupon = Coupon.objects.get(code=request.POST['del-coupon'])
            user_coupon.customers.remove(request.user)
            user_coupon.save()
            return render(request, 'order/order-result.html')
        except (KeyError, Coupon.DoesNotExist):
            return render(request, 'order/order-result.html')
    return render(request, 'order/order-result.html')

templates/order/add-address.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}ثبت آدرس جدید{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'accounts/css/add-address.css' %}">
{% endblock %}

{% block content %}
    <div class="row add-address-row">
        <div class="card col-5">
            <h5 class="alert alert-info m-2 mt-4">« آدرس خود را بادقت وارد کنید »</h5>
            <form method="post" id="add-address-form">
                {% csrf_token %}
                {% for error in form.non_field_errors %}
                    <p class="text-danger">{{ error }}*</p>
                {% endfor %}
                {% for error in form.province.errors %}
                    <p class="text-danger">{{ error }}*</p>
                {% endfor %}
                {% for error in form.city.errors %}
                    <p class="text-danger">{{ error }}*</p>
                {% endfor %}
                {% for error in form.exact_address.errors %}
                    <p class="text-danger">{{ error }}*</p>
                {% endfor %}
                {% for error in form.apartment_number.errors %}
                    <p class="text-danger">{{ error }}*</p>
                {% endfor %}
                {% for error in form.unit.errors %}
                    <p class="text-danger">{{ error }}*</p>
                {% endfor %}
                {% for error in form.zip_code.errors %}
                    <p class="text-danger">{{ error }}*</p>
                {% endfor %}
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="province">استان:</label>
                        <select class="form-control" name="province" id="province" onchange="Func(this.value)">
                            <option value=""></option>
                            <option value="  ,آذرشهر ,اسکو ,اهر ,بستان‌آباد ,بناب ,تبریز ,جلفا ,چاراویماق ,سراب ,شبستر ,عجب‌شیر ,کلیبر ,مراغه ,مرند ,ملکان ,میانه ,ورزقان ,هریس ,هشترود">
                                آذربایجان شرقی
                            </option>
                            <option value="  ,ارومیه ,اشنویه ,بوکان ,پیرانشهر ,تکاب ,چالدران ,خوی ,سردشت ,سلماس ,شاهین‌دژ ,ماکو ,مهاباد ,میاندوآب ,نقده">
                                آذربایجان غربی
                            </option>
                            <option value="  ,اردبیل ,بیله‌سوار ,پارس‌آباد ,خلخال ,کوثر ,گِرمی ,مِشگین‌شهر ,نَمین ,نیر">
                                اردبیل
                            </option>
                            <option value="  ,آران و بیدگل ,اردستان ,اصفهان ,برخوار و میمه ,تیران و کرون ,چادگان ,خمینی‌شهر ,خوانسار ,سمیرم ,شهرضا ,سمیرم سفلی ,فریدن ,فریدون‌شهر ,فلاورجان ,کاشان ,گلپایگان ,لنجان ,مبارکه ,نائین ,نجف‌آباد ,نطنز">
                                اصفهان
                            </option>
                            <option value="  ,آبدانان ,ایلام ,ایوان ,دره‌شهر ,دهلران ,شیروان و چرداول ,مهران">ایلام
                            </option>
                            <option value="  ,بوشهر ,تنگستان ,جم ,دشتستان ,دشتی,دیر ,دیلم ,کنگان ,گناوه">بوشهر</option>
                            <option value="  ,اسلام‌شهر ,پاکدشت ,تهران ,دماوند ,رباط‌کریم ,ری ,ساوجبلاغ ,شمیرانات ,شهریار ,فیروزکوه ,کرج ,نظرآباد ,ورامین">
                                تهران
                            </option>
                            <option value="  ,اردل ,بروجن ,شهرکرد ,فارسان ,کوهرنگ ,لردگان">چهارمحال و بختیاری</option>
                            <option value="  ,بیرجند ,درمیان ,سرایان ,سربیشه ,فردوس ,قائنات,نهبندان">خراسان جنوبی
                            </option>
                            <option value="  ,بردسکن ,تایباد ,تربت جام ,تربت حیدریه ,چناران ,خلیل‌آباد ,خواف ,درگز ,رشتخوار ,سبزوار ,سرخس ,فریمان ,قوچان ,کاشمر ,کلات ,گناباد ,مشهد ,مه ولات ,نیشابور">
                                خراسان رضوی
                            </option>
                            <option value="  ,اسفراین ,بجنورد ,جاجرم ,شیروان ,فاروج ,مانه و سملقان">خراسان شمالی
                            </option>
                            <option value="  ,آبادان ,امیدیه ,اندیمشک ,اهواز ,ایذه ,باغ‌ملک ,بندر ماهشهر ,بهبهان ,خرمشهر ,دزفول ,دشت آزادگان ,رامشیر ,رامهرمز ,شادگان ,شوش ,شوشتر ,گتوند ,لالی ,مسجد سلیمان,هندیجان ">
                                خوزستان
                            </option>
                            <option value="  ,ابهر ,ایجرود ,خدابنده ,خرمدره ,زنجان ,طارم ,ماه‌نشان">زنجان</option>
                            <option value="  ,دامغان ,سمنان ,شاهرود ,گرمسار ,مهدی‌شهر">سمنان</option>
                            <option value="  ,ایرانشهر ,چابهار ,خاش ,دلگان ,زابل ,زاهدان ,زهک ,سراوان ,سرباز ,کنارک ,نیک‌شهر">
                                سیستان و
                                بلوچستان
                            </option>
                            <option value="  ,آباده ,ارسنجان ,استهبان ,اقلید ,بوانات ,پاسارگاد ,جهرم ,خرم‌بید ,خنج ,داراب ,زرین‌دشت ,سپیدان ,شیراز ,فراشبند ,فسا ,فیروزآباد ,قیر و کارزین ,کازرون ,لارستان ,لامِرد ,مرودشت ,ممسنی ,مهر ,نی‌ریز">
                                فارس
                            </option>
                            <option value="  ,آبیک ,البرز ,بوئین‌زهرا ,تاکستان ,قزوین">قزوین</option>
                            <option value="  ,قم">قم</option>
                            <option value="  ,بانه ,بیجار ,دیواندره ,سروآباد ,سقز ,سنندج ,قروه ,کامیاران ,مریوان">
                                کردستان
                            </option>
                            <option value="  ,بافت ,بردسیر ,بم ,جیرفت ,راور ,رفسنجان ,رودبار جنوب ,زرند ,سیرجان ,شهر بابک ,عنبرآباد ,قلعه گنج ,کرمان ,کوهبنان ,کهنوج ,منوجان">
                                کرمان
                            </option>
                            <option value="  ,اسلام‌آباد غرب ,پاوه ,ثلاث باباجانی ,جوانرود ,دالاهو ,روانسر ,سرپل ذهاب ,سنقر ,صحنه ,قصر شیرین ,کرمانشاه ,کنگاور ,گیلان غرب ,هرسین">
                                کرمانشاه
                            </option>
                            <option value="  ,بویراحمد ,بهمئی ,دنا ,کهگیلویه ,گچساران">کهگیلویه و بویراحمد</option>
                            <option value="  ,آزادشهر ,آق‌قلا ,بندر گز ,ترکمن ,رامیان ,علی‌آباد ,کردکوی ,کلاله ,گرگان ,گنبد کاووس ,مراوه‌تپه ,مینودشت">
                                گلستان
                            </option>
                            <option value="  ,آستارا ,آستانه اشرفیه ,اَملَش ,بندر انزلی ,رشت ,رضوانشهر ,رودبار ,رودسر ,سیاهکل ,شَفت ,صومعه‌سرا ,طوالش ,فومَن ,لاهیجان ,لنگرود ,ماسال">
                                گیلان
                            </option>
                            <option value="  ,ازنا ,الیگودرز ,بروجرد ,پل‌دختر ,خرم‌آباد ,دورود ,دلفان ,سلسله ,کوهدشت">
                                لرستان
                            </option>
                            <option value="  ,آمل ,بابل ,بابلسر ,بهشهر ,تنکابن ,جویبار ,چالوس ,رامسر ,ساری ,سوادکوه ,قائم‌شهر ,گلوگاه ,محمودآباد ,نکا ,نور ,نوشهر">
                                مازندران
                            </option>
                            <option value="  ,آشتیان ,اراک ,تفرش ,خمین ,دلیجان ,زرندیه ,ساوه ,شازند ,کمیجان ,محلات">
                                مرکزی
                            </option>
                            <option value="  ,ابوموسی ,بستک ,بندر عباس ,بندر لنگه ,جاسک ,حاجی‌آباد ,شهرستان خمیر ,رودان  ,قشم ,گاوبندی ,میناب">
                                هرمزگان
                            </option>
                            <option value="  ,اسدآباد ,بهار ,تویسرکان ,رزن ,کبودرآهنگ ,ملایر ,نهاوند ,همدان">همدان
                            </option>
                            <option value="  ,ابرکوه ,اردکان ,بافق ,تفت ,خاتم ,صدوق ,طبس ,مهریز ,مِیبُد ,یزد">یزد
                            </option>
                        </select>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="city">شهر:</label>
                        <select class="form-control" name="city" id="city"></select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="exact_address">آدرس دقیق:</label>
                    <input type="text" class="form-control" name="exact_address" id="exact_address">
                </div>
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label for="No">پلاک:</label>
                        <input type="number" class="form-control" name="apartment_number" id="No">
                    </div>
                    <div class="form-group col-md-3">
                        <label for="unit">واحد:</label>
                        <input type="number" class="form-control" name="unit" id="unit">
                    </div>
                    <div class="form-group col-md-5">
                        <label for="zip_code">کد پستی:</label>
                        <input type="number" class="form-control" name="zip_code" id="zip_code">
                    </div>
                </div>
                <div id="add-address-btn-group" class="mt-3">
                    <button type="submit" class="btn btn-submit">ثبت آدرس
                    </button>
                    <button class="btn btn-danger mr-3"><a class="text-white" href="{% url 'product:all_products' %}">انصراف</a></button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script src="{% static 'order/js/add-address.js' %}"></script>
{% endblock %}

templates/order/add-item.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}ثبت سفارش{% endblock %}


{% block content %}
    <form method="POST" action="{% url 'order:add_item' %}" class="d-none" id="add-item-form">
        {% csrf_token %}
        <div class="form-group" id="product-group">
            <label for="{{ form.product.id_for_label }}"></label>
            <input type="text" class="form-control" name="product" id="id_product">
        </div>
        <div class="form-group" id="order-group">
            <label for="{{ form.order.id_for_label }}"></label>
            <input type="text" class="form-control" name="order" id="id_order" value="{{ order_id }}">
        </div>
        <div class="form-group" id="quantity-group">
            <label for="{{ form.quantity.id_for_label }}"></label>
            <input type="text" class="form-control" name="quantity" id="id_quantity">
        </div>
        <button type="submit">sub</button>
    </form>

    <form method="POST" action="{% url 'order:order_result' %}" class="d-none" id="del-coupon-form">
        {% csrf_token %}
        <div class="form-group" id="del-coupon-group">
            <label for="del-coupon"></label>
            <input type="text" class="form-control" name="del-coupon" id="del-coupon">
        </div>
        <button type="submit">sub</button>
    </form>
{% endblock %}

{% block script %}
    <script src="{% static 'order/js/add-item.js' %}"></script>
{% endblock %}

templates/order/create-order.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}ثبت سفارش{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'order/css/create-order.css' %}">
{% endblock %}

{% block modal %}
    <div class="modal fade" id="add-address-modal">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-body">
                    <h5 class="alert alert-info m-2 mt-2">« ثبت آدرس جدید »</h5>
                    <form method="post" action="{% url 'add_address' %}" id="add-address-form">
                        {% csrf_token %}

                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="add-province">استان:</label>
                                <select class="form-control province" name="add-province" id="add-province"
                                        onchange="Func(this.value)">
                                </select>
                            </div>
                            <div class="form-group col-md-6">
                                <label for="add-city">شهر:</label>
                                <select class="form-control city" name="add-city" id="add-city"></select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="add-exact_address">آدرس دقیق:</label>
                            <input type="text" class="form-control" name="add-exact_address" id="add-exact_address">
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-4">
                                <label for="add-No">پلاک:</label>
                                <input type="number" class="form-control" name="add-apartment_number" id="add-No">
                            </div>
                            <div class="form-group col-md-3">
                                <label for="add-unit">واحد:</label>
                                <input type="number" class="form-control" name="add-unit" id="add-unit">
                            </div>
                            <div class="form-group col-md-5">
                                <label for="add-zip_code">کد پستی:</label>
                                <input type="number" class="form-control" name="add-zip_code" id="add-zip_code">
                            </div>
                        </div>
                        <div id="add-address-btn-group" class="mt-3">

                            <button type="submit" class="btn btn-submit mr-0">ثبت آدرس</button>

                            <button class="btn btn-danger mr-3" data-dismiss="modal">انصراف</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="row create-order-row">
        <div class="card col-7">
            <table id="items-table" class="table table-striped" style="direction: rtl">
                <thead>
                <tr>
                    <th scope="col">تصویر</th>
                    <th scope="col">نام</th>
                    <th scope="col">رنگ</th>
                    <th scope="col">قیمت واحد</th>
                    <th scope="col">تعداد</th>
                    <th scope="col">قیمت نهایی</th>
                    <th scope="col">حذف</th>
                </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
            <div class="row">
                <div class="col-5">
                    <button class="btn btn-secondary" data-toggle="modal"
                            data-target="#add-address-modal" style="margin-top: 9.7rem;"
                            id="add-address-btn">واردکردن آدرس جدید
                    </button>
                </div>
                <div class="col-7">
                    <form method="POST" action="{% url 'check_coupon' %}" id="coupon-form"
                          enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group row" id="coupon-group">
                            <label class="col-0" for="coupon">کد تخفیف:&nbsp;</label>
                            <input type="text" class="form-control col-6" name="coupon" id="coupon">
                            <button type="submit" id="coupon-btn" class="btn btn-primary mr-2">اعمال تخفیف</button>
                        </div>
                    </form>

                    <form method="POST" id="create-order-form">
                        {% csrf_token %}
                        {% for error in form.non_field_errors %}
                            <p class="text-danger">{{ error }}*</p>
                        {% endfor %}
                        {% for error in form.shipping.errors %}
                            <p class="text-danger">{{ error }}*</p>
                        {% endfor %}
                        {% for error in form.address.errors %}
                            <p class="text-danger">{{ error }}*</p>
                        {% endfor %}
                        <div class="form-group row" id="shipping-group">
                            <label class="col-0" for="{{ form.shipping.id_for_label }}">نحوه پست:&nbsp;</label>
                            {{ form.shipping }}
                        </div>
                        <div class="form-group row" id="address-group">
                            <label class="col-0" for="{{ form.address.id_for_label }}">آدرس:&nbsp;</label>
                            <select type="text" class="form-control col-8 mr-3" name="address" id="id_address">
                                {% for address in user.addresses.all %}
                                    <option value="{{ address.id }}">{{ address }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="mt-5">
                            <button type="submit" class="btn btn-submit" id="payment-btn">پرداخت
                                و ثبت نهایی سفارش
                            </button>
                            <button type="button" class="btn btn-danger mr-3"><a class="text-white"
                                                                                 href="{% url 'product:all_products' %}">انصراف</a>
                            </button>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

{% block script %}
    <script src="{% static 'order/js/create-order.js' %}"></script>
{% endblock %}

templates/order/order-result.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}ثبت سفارش{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'order/css/order-result.css' %}">
{% endblock %}


{% block content %}
    <div class="row order-result-row">
        <div class="card col-7">
            <i class="text-success fa fa-fw fa-check-circle"></i>
            <h3 class="alert alert-success text-center mt-2">.سفارش شما با موفقیت پرداخت و ثبت گردید</h3>
            <div class="alert alert-secondary">
                <h5 class="text-center">.از اینکه کالاشاپ را برای خرید انتخاب کردید، از شما سپاسگزاریم</h5>

                <h5 id="order-id" class="text-center text-dark"></h5>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script src="{% static 'order/js/order-result.js' %}"></script>
{% endblock %}